### ISSUE TITLE
Does sequiter provide Asian (Urdu) language support?

### ISSUE THREAD

**Issue by mirfan899** [sequitur-g2p/sequitur-g2p#13]
I'm trying to run sequiter on Urdu and having some issues related to encoding:

Here is the output of error:

```shell
Traceback (most recent call last):
  File "/home/irfan/kaldi/tools/sequitur-g2p/bin/g2p.py", line 4, in <module>
    __import__('pkg_resources').run_script('sequitur==1.0a1', 'g2p.py')
  File "/home/irfan/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/irfan/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1438, in run_script
    exec(code, namespace, namespace)
  File "/home/irfan/kaldi/tools/sequitur-g2p/lib/python2.7/site-packages/sequitur-1.0a1-py2.7-linux-x86_64.egg/EGG-INFO/scripts/g2p.py", line 269, in <module>
    tool.run(main, options, args)
  File "/home/irfan/kaldi/tools/sequitur-g2p/lib/python2.7/site-packages/sequitur-1.0a1-py2.7-linux-x86_64.egg/tool.py", line 63, in run
    status = runMain(main, options, args)
  File "/home/irfan/kaldi/tools/sequitur-g2p/lib/python2.7/site-packages/sequitur-1.0a1-py2.7-linux-x86_64.egg/tool.py", line 99, in runMain
    status = main(options, args)
  File "/home/irfan/kaldi/tools/sequitur-g2p/lib/python2.7/site-packages/sequitur-1.0a1-py2.7-linux-x86_64.egg/EGG-INFO/scripts/g2p.py", line 215, in main
    mainApply(translator, options)
  File "/home/irfan/kaldi/tools/sequitur-g2p/lib/python2.7/site-packages/sequitur-1.0a1-py2.7-linux-x86_64.egg/EGG-INFO/scripts/g2p.py", line 183, in mainApply
    print(('%s\t%s' % (word, ' '.join(result))))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0621' in position 0: ordinal not in range(128)
```

**Comment by jtrmal** [comment]
G2p.py has a parameter --encoding that can be used to specify the encoding
- it should work, I have used sequitur for around 50 different languages,
including Pashto and several variants of Arabic
Y.

**Comment by langep** [comment]
This might be an issue introduced by me. Can you share some a sample input and command to reproduce the problem?

**Comment by mirfan899** [comment]
The issue was related to encoding as stated by @jtrmal. Here is the command which I use now to fix the issue

```shell
g2p.py --model=conf/g2p_model --encoding UTF-8 --apply $locdict/vocab-oov.txt > $locdict/lexicon-oov.txt
```

**Comment by jtrmal** [comment]
Then I will consider this as resolved.
