### ISSUE TITLE
Ascii encoding error

### ISSUE THREAD

**Issue by pehonnet** [sequitur-g2p/sequitur-g2p#32]
Issue was (on German data):
```
Traceback (most recent call last):
  File "~/Tools/venv/g2p-sequitur/lib/python3.5/site-packages/g2p.py", line 269, in <module>
    tool.run(main, options, args)
  File "~/Tools/venv/g2p-sequitur/lib/python3.5/site-packages/tool.py", line 63, in run
    status = runMain(main, options, args)
  File "~/Tools/venv/g2p-sequitur/lib/python3.5/site-packages/tool.py", line 99, in runMain
    status = main(options, args)
  File "~/Tools/venv/g2p-sequitur/lib/python3.5/site-packages/g2p.py", line 215, in main
    mainApply(translator, options)
  File "~/Tools/venv/g2p-sequitur/lib/python3.5/site-packages/g2p.py", line 183, in mainApply
    print(('%s\t%s' % (word, ' '.join(result))))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 5-6: ordinal not in range(128)
```

This fix seems to work with python3.5 (on CentOS 7):
In g2p.py, replace line 183
```
print(('%s\t%s' % (word, ' '.join(result))))
```
by
```
print(('%s\t%s' % (word.encode("utf-8"), ' '.join(result))))
```

**Comment by el2727** [comment]
Got the same errors for non-Roman languages - the fixes are slightly different but also work, in this patch file:
[patchfile.txt](https://github.com/sequitur-g2p/sequitur-g2p/files/2560324/patchfile.txt)

**Comment by jtrmal** [comment]
thanks for the report. I'm currently overcome by other things but I'm
keeping this in mind.
If you could send me (offline) an example fail that causes the problems,
I'd appreciate it.
Thanks,
y.

**Comment by jtrmal** [comment]
this should be resolved, @pehonnet please test.
