### ISSUE TITLE
ascii endoing error when in apply

### ISSUE THREAD

**Issue by wonkyuml** [sequitur-g2p/sequitur-g2p#38]
I still see errors when apply mode. Training mode worked out nicely with recent patch. 

Used command: 
split -n l/1/10 data/local/dict_g2p//wordlist.txt | g2p.py -V 0.9 --variants-number 3 --encoding utf-8 --model exp/g2p//g2p.model.final --apply - > data/local/dict_g2p//output.1 

 Traceback (most recent call last):
   File "/data-local1/kaldi/tools/sequitur-g2p/bin/g2p.py", line 4, in <module>
     __import__('pkg_resources').run_script('sequitur==1.0a1', 'g2p.py')
   File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 658, in run_script
     self.require(requires)[0].run_script(script_name, ns)
   File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1438, in run_script
     exec(code, namespace, namespace)
   File "/data-local1/kaldi/tools/sequitur-g2p/lib/python2.7/site-packages/sequitur-1.0a1-py2.7-linux-x86_64.egg/EGG-INFO/scripts/g2p.py", line 304, in <module>
     tool.run(main, options, args)
   File "/data-local1/kaldi/tools/sequitur-g2p/lib/python2.7/site-packages/sequitur-1.0a1-py2.7-linux-x86_64.egg/tool.py", line 63, in run
     status = runMain(main, options, args)
   File "/data-local1/kaldi/tools/sequitur-g2p/lib/python2.7/site-packages/sequitur-1.0a1-py2.7-linux-x86_64.egg/tool.py", line 99, in runMain
     status = main(options, args)
   File "/data-local1/kaldi/tools/sequitur-g2p/lib/python2.7/site-packages/sequitur-1.0a1-py2.7-linux-x86_64.egg/EGG-INFO/scripts/g2p.py", line 244, in main
     mainApply(translator, options)
   File "/data-local1/kaldi/tools/sequitur-g2p/lib/python2.7/site-packages/sequitur-1.0a1-py2.7-linux-x86_64.egg/EGG-INFO/scripts/g2p.py", line 179, in mainApply
     (word, nVariants, posterior, ' '.join(result))))
 UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 3: ordinal not in range(128)

**Comment by jtrmal** [comment]
Thanks for testing it. I will look into it tomorrow.
Y.

**Comment by jtrmal** [comment]
resolved in #39
